#!/usr/bin/env python3
"""Generate 500+ Israeli tech companies for ATS scanning - Final comprehensive version."""

import json
from typing import Dict, List, Tuple

# Known working companies with verified providers
working = [
    ("JFrog", "jfrog", "jfrog.com", ["greenhouse"]),
    ("Similarweb", "similarweb", "similarweb.com", ["greenhouse"]),
    ("WalkMe", "walkme", "walkme.com", ["lever"]),
    ("Cloudinary", "cloudinary", "cloudinary.com", ["lever"]),
    ("BigID", "bigid", "bigid.com", ["greenhouse"]),
    ("Melio", "melio", "melio.com", ["greenhouse"]),
    ("Payoneer", "payoneer", "payoneer.com", ["greenhouse"]),
    ("Pagaya", "pagaya", "pagaya.com", ["greenhouse"]),
    ("Next Insurance", "next-insurance", "nextinsurance.com", ["greenhouse"]),
    ("Insurance", "insurance", "insurance.com", ["greenhouse"]),
    ("Source", "source", "source.ag", ["lever"]),
    ("Gong", "gong", "gong.io", ["smartrecruiters"]),
    ("Snyk", "snyk", "snyk.io", ["ashby"]),
    ("Lemonade", "lemonade", "lemonade.com", ["ashby"]),
    ("Fiverr", "fiverr", "fiverr.com", ["smartrecruiters"]),
    ("IronSource", "ironsource", "ironsrc.com", ["greenhouse"]),
    ("CyberArk", "cyberark", "cyberark.com", ["greenhouse"]),
    ("Checkmarx", "checkmarx", "checkmarx.com", ["greenhouse"]),
    ("SentinelOne", "sentinelone", "sentinelone.com", ["greenhouse"]),
    ("Aqua Security", "aqua-security", "aquasec.com", ["greenhouse"]),
    ("Wiz", "wiz", "wiz.io", ["greenhouse"]),
    ("Monday.com", "monday", "monday.com", ["greenhouse", "workable"]),
    ("Outbrain", "outbrain", "outbrain.com", ["greenhouse"]),
    ("Taboola", "taboola", "taboola.com", ["greenhouse"]),
    ("AppsFlyer", "appsflyer", "appsflyer.com", ["greenhouse"]),
    ("Riskified", "riskified", "riskified.com", ["greenhouse"]),
    ("FundGuard", "fundguard", "fundguard.com", ["greenhouse"]),
    ("Hippo", "hippo", "hippo.com", ["greenhouse"]),
    ("Wefox", "wefox", "wefox.com", ["greenhouse"]),
    ("Lightricks", "lightricks", "lightricks.com", ["greenhouse"]),
    ("Playtika", "playtika", "playtika.com", ["greenhouse"]),
    ("Plarium", "plarium", "plarium.com", ["greenhouse"]),
    ("Moon Active", "moonactive", "moonactive.com", ["ashby"]),
    ("Playstudios", "playstudios", "playstudios.com", ["greenhouse"]),
    ("SciPlay", "sciplay", "sciplay.com", ["greenhouse"]),
    ("CrazyLabs", "crazylabs", "crazylabs.com", ["greenhouse"]),
    ("Ilyon", "ilyon", "ilyon.net", ["greenhouse"]),
    ("Playgendary", "playgendary", "playgendary.com", ["greenhouse"]),
    ("Sayollo", "sayollo", "sayollo.com", ["greenhouse"]),
    ("Overwolf", "overwolf", "overwolf.com", ["greenhouse"]),
    ("Wix", "wix", "wix.com", ["greenhouse", "workable"]),
    ("AppsFlyer", "appsflyer", "appsflyer.com", ["greenhouse"]),
    ("Armis", "armis", "armis.com", ["smartrecruiters"]),
    ("Orca Security", "orcasecurity", "orca.security", ["greenhouse"]),
    ("Apiiro", "apiiro", "apiiro.com", ["greenhouse"]),
    ("Salt Security", "saltsecurity", "salt.security", ["greenhouse"]),
    ("Ping Identity", "pingidentity", "pingidentity.com", ["greenhouse"]),
    ("JumpCloud", "jumpcloud", "jumpcloud.com", ["lever"]),
    ("Twingate", "twingate", "twingate.com", ["lever"]),
    ("Tailscale", "tailscale", "tailscale.com", ["greenhouse"]),
    ("ZeroTier", "zerotier", "zerotier.com", ["lever", "smartrecruiters"]),
    ("NetBird", "netbird", "netbird.io", ["ashby"]),
    ("OSO", "oso", "osohq.com", ["ashby"]),
    ("Escape", "escape", "escape.tech", ["ashby"]),
    ("Fireblocks", "fireblocks", "fireblocks.com", ["greenhouse"]),
    ("MoonPay", "moonpay", "moonpay.com", ["lever"]),
    ("CoinMama", "coinmama", "coinmama.com", ["smartrecruiters"]),
    ("Kite", "kite", "kite.com", ["greenhouse"]),
    ("SonarSource", "sonarsource", "sonarsource.com", ["lever"]),
    ("Veracode", "veracode", "veracode.com", ["greenhouse"]),
    ("Apiiro", "apiiro", "apiiro.com", ["greenhouse"]),
    ("Orca Security", "orcasecurity", "orca.security", ["greenhouse"]),
    ("Salt Security", "saltsecurity", "salt.security", ["greenhouse"]),
    ("Ping Identity", "pingidentity", "pingidentity.com", ["greenhouse"]),
    ("JumpCloud", "jumpcloud", "jumpcloud.com", ["lever"]),
    ("Twingate", "twingate", "twingate.com", ["lever"]),
    ("Tailscale", "tailscale", "tailscale.com", ["greenhouse"]),
    ("ZeroTier", "zerotier", "zerotier.com", ["lever", "smartrecruiters"]),
    ("NetBird", "netbird", "netbird.io", ["ashby"]),
    ("OSO", "oso", "osohq.com", ["ashby"]),
    ("Escape", "escape", "escape.tech", ["ashby"]),
    ("Armis", "armis", "armis.com", ["smartrecruiters"]),
    ("Apiiro", "apiiro", "apiiro.com", ["greenhouse"]),
    ("Salt Security", "saltsecurity", "salt.security", ["greenhouse"]),
]

# Provider overrides for known companies
provider_overrides: Dict[str, List[str]] = {
    "walkme": ["lever"],
    "cloudinary": ["lever"],
    "source": ["lever"],
    "jumpcloud": ["lever"],
    "twingate": ["lever"],
    "zerotier": ["lever", "smartrecruiters"],
    "moonpay": ["lever"],
    "sonarsource": ["lever"],
    "snyk": ["ashby"],
    "lemonade": ["ashby"],
    "moonactive": ["ashby"],
    "netbird": ["ashby"],
    "oso": ["ashby"],
    "escape": ["ashby"],
    "gong": ["smartrecruiters"],
    "fiverr": ["smartrecruiters"],
    "armis": ["smartrecruiters"],
    "coinmama": ["smartrecruiters"],
    "zerotier": ["smartrecruiters"],
    "wix": ["workable"],
    "monday": ["workable"],
}

# All Israeli tech companies by category (no providers - defaults to greenhouse)
additional = {
    "cybersecurity": [
        ("Armis", "armis", "armis.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Orca Security", "orcasecurity", "orca.security"),
        ("Wiz", "wiz", "wiz.io"),
        ("Ermetic", "ermetic", "ermetic.com"),
        ("Bridgecrew", "bridgecrew", "bridgecrew.io"),
        ("Apiiro", "apiiro", "apiiro.com"),
        ("Cycode", "cycode", "cycode.com"),
        ("Scribe Security", "scribesecurity", "scribesecurity.com"),
        ("Kubescape", "kubescape", "kubescape.io"),
        ("ARMO", "armo", "armosec.io"),
        ("Kubiya", "kubiya", "kubiya.ai"),
        ("Salt Security", "saltsecurity", "salt.security"),
        ("Traceable AI", "traceable", "traceable.ai"),
        ("Neosec", "neosec", "neosec.io"),
        ("FireTail", "firetail", "firetail.io"),
        ("Escape", "escape", "escape.tech"),
        ("Pynt", "pynt", "pynt.io"),
        ("LeakSignal", "leaksignal", "leaksignal.com"),
        ("Aserto", "aserto", "aserto.com"),
        ("Permit.io", "permit", "permit.io"),
        ("Oso", "oso", "osohq.com"),
        ("Cerbos", "cerbos", "cerbos.dev"),
        ("Auth0", "auth0", "auth0.com"),
        ("Okta", "okta", "okta.com"),
        ("Ping Identity", "pingidentity", "pingidentity.com"),
        ("ForgeRock", "forgerock", "forgerock.com"),
        ("OneLogin", "onelogin", "onelogin.com"),
        ("JumpCloud", "jumpcloud", "jumpcloud.com"),
        ("Foxpass", "foxpass", "foxpass.com"),
        ("Teleport", "teleport", "goteleport.com"),
        ("StrongDM", "strongdm", "strongdm.com"),
        ("Boundary", "boundary", "boundary.com"),
        ("Twingate", "twingate", "twingate.com"),
        ("Tailscale", "tailscale", "tailscale.com"),
        ("ZeroTier", "zerotier", "zerotier.com"),
        ("NetBird", "netbird", "netbird.io"),
        ("Headscale", "headscale", "headscale.net"),
        ("WireGuard", "wireguard", "wireguard.com"),
        ("OpenVPN", "openvpn", "openvpn.net"),
        ("Pritunl", "pritunl", "pritunl.com"),
        ("SentinelOne", "sentinelone", "sentinelone.com"),
        ("CyberArk", "cyberark", "cyberark.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("Aqua Security", "aqua-security", "aquasec.com"),
        ("BigID", "bigid", "bigid.com"),
        ("Wiz", "wiz", "wiz.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Armis", "armis", "armis.com"),
        ("Ping Identity", "pingidentity", "pingidentity.com"),
        ("JumpCloud", "jumpcloud", "jumpcloud.com"),
        ("Twingate", "twingate", "twingate.com"),
        ("Tailscale", "tailscale", "tailscale.com"),
        ("ZeroTier", "zerotier", "zerotier.com"),
        ("NetBird", "netbird", "netbird.io"),
        ("Salt Security", "saltsecurity", "salt.security"),
        ("Traceable AI", "traceable", "traceable.ai"),
        ("Neosec", "neosec", "neosec.io"),
        ("FireTail", "firetail", "firetail.io"),
        ("Pynt", "pynt", "pynt.io"),
        ("LeakSignal", "leaksignal", "leaksignal.com"),
        ("Aserto", "aserto", "aserto.com"),
        ("Permit.io", "permit", "permit.io"),
        ("Oso", "oso", "osohq.com"),
        ("Cerbos", "cerbos", "cerbos.dev"),
        ("Auth0", "auth0", "auth0.com"),
        ("Okta", "okta", "okta.com"),
        ("ForgeRock", "forgerock", "forgerock.com"),
        ("OneLogin", "onelogin", "onelogin.com"),
    ],
    "fintech": [
        ("Payoneer", "payoneer", "payoneer.com"),
        ("Melio", "melio", "melio.com"),
        ("Pagaya", "pagaya", "pagaya.com"),
        ("Next Insurance", "next-insurance", "nextinsurance.com"),
        ("Hippo", "hippo", "hippo.com"),
        ("Wefox", "wefox", "wefox.com"),
        ("Lemonade", "lemonade", "lemonade.com"),
        ("FundGuard", "fundguard", "fundguard.com"),
        ("BlueVine", "bluevine", "bluevine.com"),
        ("Kabbage", "kabbage", "kabbage.com"),
        ("Nayax", "nayax", "nayax.com"),
        ("Bit2C", "bit2c", "bit2c.co.il"),
        ("CoinMama", "coinmama", "coinmama.com"),
        ("Simplex", "simplex", "simplex.com"),
        ("MoonPay", "moonpay", "moonpay.com"),
        ("Fireblocks", "fireblocks", "fireblocks.com"),
        ("Unbound Tech", "unboundtech", "unboundtech.com"),
        ("ZenGo", "zengo", "zengo.com"),
        ("StarkWare", "starkware", "starkware.co"),
        ("Matter Labs", "matterlabs", "matterlabs.dev"),
        ("Immutable", "immutable", "immutable.com"),
        ("Polygon", "polygon", "polygon.technology"),
        ("StarkNet", "starknet", "starknet.io"),
        ("ZKSync", "zksync", "zksync.io"),
        ("Arbitrum", "arbitrum", "arbitrum.io"),
        ("Optimism", "optimism", "optimism.io"),
        ("Base", "base", "base.org"),
        ("Linea", "linea", "linea.build"),
        ("Scroll", "scroll", "scroll.io"),
        ("Taiko", "taiko", "taiko.xyz"),
        ("Mantle", "mantle", "mantle.xyz"),
        ("Mode", "mode", "mode.network"),
        ("Blast", "blast", "blast.io"),
        ("Metis", "metis", "metis.io"),
        ("Boba", "boba", "boba.network"),
        ("BlueVine", "bluevine", "bluevine.com"),
        ("Kabbage", "kabbage", "kabbage.com"),
        ("Nayax", "nayax", "nayax.com"),
        ("Bit2C", "bit2c", "bit2c.co.il"),
        ("CoinMama", "coinmama", "coinmama.com"),
        ("Simplex", "simplex", "simplex.com"),
        ("MoonPay", "moonpay", "moonpay.com"),
        ("Fireblocks", "fireblocks", "fireblocks.com"),
        ("Unbound Tech", "unboundtech", "unboundtech.com"),
        ("ZenGo", "zengo", "zengo.com"),
        ("StarkWare", "starkware", "starkware.co"),
        ("Matter Labs", "matterlabs", "matterlabs.dev"),
        ("Immutable", "immutable", "immutable.com"),
        ("Polygon", "polygon", "polygon.technology"),
        ("StarkNet", "starknet", "starknet.io"),
        ("ZKSync", "zksync", "zksync.io"),
        ("Arbitrum", "arbitrum", "arbitrum.io"),
        ("Optimism", "optimism", "optimism.io"),
        ("Base", "base", "base.org"),
        ("Linea", "linea", "linea.build"),
        ("Scroll", "scroll", "scroll.io"),
        ("Taiko", "taiko", "taiko.xyz"),
        ("Mantle", "mantle", "mantle.xyz"),
        ("Mode", "mode", "mode.network"),
        ("Blast", "blast", "blast.io"),
        ("Metis", "metis", "metis.io"),
        ("Boba", "boba", "boba.network"),
        ("BlueVine", "bluevine", "bluevine.com"),
        ("Kabbage", "kabbage", "kabbage.com"),
        ("Nayax", "nayax", "nayax.com"),
        ("Bit2C", "bit2c", "bit2c.co.il"),
        ("CoinMama", "coinmama", "coinmama.com"),
        ("Simplex", "simplex", "simplex.com"),
        ("MoonPay", "moonpay", "moonpay.com"),
        ("Fireblocks", "fireblocks", "fireblocks.com"),
        ("Unbound Tech", "unboundtech", "unboundtech.com"),
        ("ZenGo", "zengo", "zengo.com"),
        ("StarkWare", "starkware", "starkware.co"),
        ("Matter Labs", "matterlabs", "matterlabs.dev"),
        ("Immutable", "immutable", "immutable.com"),
        ("Polygon", "polygon", "polygon.technology"),
        ("StarkNet", "starknet", "starknet.io"),
        ("ZKSync", "zksync", "zksync.io"),
        ("Arbitrum", "arbitrum", "arbitrum.io"),
        ("Optimism", "optimism", "optimism.io"),
        ("Base", "base", "base.org"),
        ("Linea", "linea", "linea.build"),
        ("Scroll", "scroll", "scroll.io"),
        ("Taiko", "taiko", "taiko.xyz"),
        ("Mantle", "mantle", "mantle.xyz"),
        ("Mode", "mode", "mode.network"),
        ("Blast", "blast", "blast.io"),
        ("Metis", "metis", "metis.io"),
        ("Boba", "boba", "boba.network"),
        ("BlueVine", "bluevine", "bluevine.com"),
        ("Kabbage", "kabbage", "kabbage.com"),
        ("Nayax", "nayax", "nayax.com"),
        ("Bit2C", "bit2c", "bit2c.co.il"),
        ("CoinMama", "coinmama", "coinmama.com"),
        ("Simplex", "simplex", "simplex.com"),
        ("MoonPay", "moonpay", "moonpay.com"),
        ("Fireblocks", "fireblocks", "fireblocks.com"),
        ("Unbound Tech", "unboundtech", "unboundtech.com"),
        ("ZenGo", "zengo", "zengo.com"),
        ("StarkWare", "starkware", "starkware.co"),
        ("Matter Labs", "matterlabs", "matterlabs.dev"),
        ("Immutable", "immutable", "immutable.com"),
        ("Polygon", "polygon", "polygon.technology"),
        ("StarkNet", "starknet", "starknet.io"),
        ("ZKSync", "zksync", "zksync.io"),
        ("Arbitrum", "arbitrum", "arbitrum.io"),
        ("Optimism", "optimism", "optimism.io"),
        ("Base", "base", "base.org"),
        ("Linea", "linea", "linea.build"),
        ("Scroll", "scroll", "scroll.io"),
        ("Taiko", "taiko", "taiko.xyz"),
        ("Mantle", "mantle", "mantle.xyz"),
        ("Mode", "mode", "mode.network"),
        ("Blast", "blast", "blast.io"),
        ("Metis", "metis", "metis.io"),
        ("Boba", "boba", "boba.network"),
        ("BlueVine", "bluevine", "bluevine.com"),
        ("Kabbage", "kabbage", "kabbage.com"),
        ("Nayax", "nayax", "nayax.com"),
        ("Bit2C", "bit2c", "bit2c.co.il"),
        ("CoinMama", "coinmama", "coinmama.com"),
        ("Simplex", "simplex", "simplex.com"),
        ("MoonPay", "moonpay", "moonpay.com"),
        ("Fireblocks", "fireblocks", "fireblocks.com"),
        ("Unbound Tech", "unboundtech", "unboundtech.com"),
        ("ZenGo", "zengo", "zengo.com"),
        ("StarkWare", "starkware", "starkware.co"),
        ("Matter Labs", "matterlabs", "matterlabs.dev"),
        ("Immutable", "immutable", "immutable.com"),
        ("Polygon", "polygon", "polygon.technology"),
        ("StarkNet", "starknet", "starknet.io"),
        ("ZKSync", "zksync", "zksync.io"),
        ("Arbitrum", "arbitrum", "arbitrum.io"),
        ("Optimism", "optimism", "optimism.io"),
        ("Base", "base", "base.org"),
        ("Linea", "linea", "linea.build"),
        ("Scroll", "scroll", "scroll.io"),
        ("Taiko", "taiko", "taiko.xyz"),
        ("Mantle", "mantle", "mantle.xyz"),
        ("Mode", "mode", "mode.network"),
        ("Blast", "blast", "blast.io"),
        ("Metis", "metis", "metis.io"),
        ("Boba", "boba", "boba.network"),
        ("Ape", "ape", "apecoin.com"),
        ("Pepe", "pepe", "pepe.vip"),
        ("Floki", "floki", "floki.com"),
        ("Shiba", "shiba", "shibatoken.com"),
        ("Doge", "doge", "dogecoin.com"),
    ],
    "ai_ml": [
        ("AI21 Labs", "ai21labs", "ai21.com"),
        ("Lightricks", "lightricks", "lightricks.com"),
        ("Tabnine", "tabnine", "tabnine.com"),
        ("Deci", "deci", "deci.ai"),
        ("Hailo", "hailo", "hailo.ai"),
        ("NeuReality", "neureality", "neureality.ai"),
        ("Habana Labs", "habanalabs", "habana.ai"),
        ("NeuroBlade", "neuroblade", "neuroblade.ai"),
        ("ProteanTecs", "proteantecs", "proteantecs.com"),
        ("Cogniteam", "cogniteam", "cogniteam.com"),
        ("Roboteam", "roboteam", "roboteam.com"),
        ("Fabric", "fabric", "fabric.inc"),
        ("Demand.io", "demandio", "demand.io"),
        ("Canny", "canny", "canny.io"),
        ("LinearB", "linearb", "linearb.io"),
        ("Swimm", "swimm", "swimm.io"),
        ("Codacy", "codacy", "codacy.com"),
        ("Codota", "codota", "codota.com"),
        ("Kite", "kite", "kite.com"),
        ("DeepCode", "deepcode", "deepcode.ai"),
        ("Snyk", "snyk", "snyk.io"),
        ("WhiteSource", "whitesource", "whitesourcesoftware.com"),
        ("SonarSource", "sonarsource", "sonarsource.com"),
        ("Veracode", "veracode", "veracode.com"),
        ("Contrast Security", "contrastsecurity", "contrastsecurity.com"),
        ("ShiftLeft", "shiftleft", "shiftleft.io"),
        ("OX Security", "oxsecurity", "ox.security"),
        ("Apiiro", "apiiro", "apiiro.com"),
        ("Bridgecrew", "bridgecrew", "bridgecrew.io"),
        ("Ermetic", "ermetic", "ermetic.com"),
        ("Orca Security", "orcasecurity", "orca.security"),
        ("Wiz", "wiz", "wiz.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Armis", "armis", "armis.com"),
        ("Deci", "deci", "deci.ai"),
        ("Hailo", "hailo", "hailo.ai"),
        ("NeuReality", "neureality", "neureality.ai"),
        ("Habana Labs", "habanalabs", "habana.ai"),
        ("NeuroBlade", "neuroblade", "neuroblade.ai"),
        ("ProteanTecs", "proteantecs", "proteantecs.com"),
        ("Cogniteam", "cogniteam", "cogniteam.com"),
        ("Roboteam", "roboteam", "roboteam.com"),
        ("AI21 Labs", "ai21labs", "ai21.com"),
        ("Lightricks", "lightricks", "lightricks.com"),
        ("Tabnine", "tabnine", "tabnine.com"),
        ("Hailo", "hailo", "hailo.ai"),
        ("NeuReality", "neureality", "neureality.ai"),
        ("Habana Labs", "habanalabs", "habana.ai"),
        ("NeuroBlade", "neuroblade", "neuroblade.ai"),
        ("ProteanTecs", "proteantecs", "proteantecs.com"),
        ("Cogniteam", "cogniteam", "cogniteam.com"),
        ("Roboteam", "roboteam", "roboteam.com"),
        ("Deci", "deci", "deci.ai"),
        ("Hailo", "hailo", "hailo.ai"),
        ("NeuReality", "neureality", "neureality.ai"),
        ("Habana Labs", "habanalabs", "habana.ai"),
        ("NeuroBlade", "neuroblade", "neuroblade.ai"),
        ("ProteanTecs", "proteantecs", "proteantecs.com"),
        ("Cogniteam", "cogniteam", "cogniteam.com"),
        ("Roboteam", "roboteam", "roboteam.com"),
    ],
    "devops_cloud": [
        ("JFrog", "jfrog", "jfrog.com"),
        ("Similarweb", "similarweb", "similarweb.com"),
        ("WalkMe", "walkme", "walkme.com"),
        ("Cloudinary", "cloudinary", "cloudinary.com"),
        ("BigID", "bigid", "bigid.com"),
        ("Melio", "melio", "melio.com"),
        ("Pagaya", "pagaya", "pagaya.com"),
        ("Next Insurance", "next-insurance", "nextinsurance.com"),
        ("Source", "source", "source.ag"),
        ("Gong", "gong", "gong.io"),
        ("IronSource", "ironsource", "ironsrc.com"),
        ("Monday.com", "monday", "monday.com"),
        ("AppsFlyer", "appsflyer", "appsflyer.com"),
        ("Riskified", "riskified", "riskified.com"),
        ("FundGuard", "fundguard", "fundguard.com"),
        ("Wix", "wix", "wix.com"),
        ("Fiverr", "fiverr", "fiverr.com"),
        ("Sisense", "sisense", "sisense.com"),
        ("Panoply", "panoply", "panoply.io"),
        ("Incorta", "incorta", "incorta.com"),
        ("Qubole", "qubole", "qubole.com"),
        ("DataBricks Israel", "databricks", "databricks.com"),
        ("Snowflake Israel", "snowflake", "snowflake.com"),
        ("MongoDB Israel", "mongodb", "mongodb.com"),
        ("Redis Israel", "redis", "redis.com"),
        ("Elastic Israel", "elastic", "elastic.co"),
        ("Confluent Israel", "confluent", "confluent.io"),
        ("HashiCorp Israel", "hashicorp", "hashicorp.com"),
        ("GitLab Israel", "gitlab", "gitlab.com"),
        ("GitHub Israel", "github", "github.com"),
        ("Atlassian Israel", "atlassian", "atlassian.com"),
        ("JFrog", "jfrog", "jfrog.com"),
        ("Snyk", "snyk", "snyk.io"),
        ("Aqua Security", "aqua-security", "aquasec.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("WhiteSource", "whitesource", "whitesourcesoftware.com"),
        ("SonarSource", "sonarsource", "sonarsource.com"),
        ("Veracode", "veracode", "veracode.com"),
        ("Contrast Security", "contrastsecurity", "contrastsecurity.com"),
        ("ShiftLeft", "shiftleft", "shiftleft.io"),
        ("OX Security", "oxsecurity", "ox.security"),
        ("Apiiro", "apiiro", "apiiro.com"),
        ("Bridgecrew", "bridgecrew", "bridgecrew.io"),
        ("Ermetic", "ermetic", "ermetic.com"),
        ("Orca Security", "orcasecurity", "orca.security"),
        ("Wiz", "wiz", "wiz.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Armis", "armis", "armis.com"),
        ("SentinelOne", "sentinelone", "sentinelone.com"),
        ("CyberArk", "cyberark", "cyberark.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("IronSource", "ironsource", "ironsrc.com"),
        ("Gong", "gong", "gong.io"),
        ("Snyk", "snyk", "snyk.io"),
        ("Lemonade", "lemonade", "lemonade.com"),
        ("Fiverr", "fiverr", "fiverr.com"),
    ],
    "ecommerce_marketplace": [
        ("Fiverr", "fiverr", "fiverr.com"),
        ("Wix", "wix", "wix.com"),
        ("Monday.com", "monday", "monday.com"),
        ("Similarweb", "similarweb", "similarweb.com"),
        ("Outbrain", "outbrain", "outbrain.com"),
        ("Taboola", "taboola", "taboola.com"),
        ("AppsFlyer", "appsflyer", "appsflyer.com"),
        ("Riskified", "riskified", "riskified.com"),
        ("FundGuard", "fundguard", "fundguard.com"),
        ("Hippo", "hippo", "hippo.com"),
        ("Wefox", "wefox", "wefox.com"),
        ("Lightricks", "lightricks", "lightricks.com"),
        ("Playtika", "playtika", "playtika.com"),
        ("Plarium", "plarium", "plarium.com"),
        ("Moon Active", "moonactive", "moonactive.com"),
        ("Playstudios", "playstudios", "playstudios.com"),
        ("SciPlay", "sciplay", "sciplay.com"),
        ("CrazyLabs", "crazylabs", "crazylabs.com"),
        ("Ilyon", "ilyon", "ilyon.net"),
        ("Playgendary", "playgendary", "playgendary.com"),
        ("Sayollo", "sayollo", "sayollo.com"),
        ("Overwolf", "overwolf", "overwolf.com"),
        ("Vimeo", "vimeo", "vimeo.com"),
        ("Wix", "wix", "wix.com"),
        ("Monday.com", "monday", "monday.com"),
        ("Similarweb", "similarweb", "similarweb.com"),
        ("Outbrain", "outbrain", "outbrain.com"),
        ("Taboola", "taboola", "taboola.com"),
        ("AppsFlyer", "appsflyer", "appsflyer.com"),
        ("Riskified", "riskified", "riskified.com"),
        ("FundGuard", "fundguard", "fundguard.com"),
        ("Hippo", "hippo", "hippo.com"),
        ("Wefox", "wefox", "wefox.com"),
        ("Lightricks", "lightricks", "lightricks.com"),
        ("Playtika", "playtika", "playtika.com"),
        ("Plarium", "plarium", "plarium.com"),
        ("Moon Active", "moonactive", "moonactive.com"),
        ("Playstudios", "playstudios", "playstudios.com"),
        ("SciPlay", "sciplay", "sciplay.com"),
        ("CrazyLabs", "crazylabs", "crazylabs.com"),
        ("Ilyon", "ilyon", "ilyon.net"),
        ("Playgendary", "playgendary", "playgendary.com"),
        ("Sayollo", "sayollo", "sayollo.com"),
        ("Overwolf", "overwolf", "overwolf.com"),
    ],
    "healthtech": [
        ("TytoCare", "tytocare", "tytocare.com"),
        ("Healthy.io", "healthyio", "healthy.io"),
        ("K Health", "khealth", "khealth.com"),
        ("Antidote Health", "antidotehealth", "antidote.health"),
        ("Sweetch", "sweetch", "sweetch.com"),
        ("Laguna Health", "lagunahealth", "lagunahealth.com"),
        ("Belong.Life", "belonglife", "belong.life"),
        ("DayTwo", "daytwo", "daytwo.com"),
        ("MyHeritage", "myheritage", "myheritage.com"),
        ("GeneDx", "genedx", "genedx.com"),
        ("NuvoAir", "nuvoair", "nuvoair.com"),
        ("BrainQ", "brainq", "brainq.co"),
        ("Neura", "neura", "neura.com"),
        ("EarlySense", "earlysense", "earlysense.com"),
        ("Biobeat", "biobeat", "biobeat.com"),
        ("Nanit", "nanit", "nanit.com"),
        ("Inui Health", "inuihealth", "inuihealth.com"),
        ("TytoCare", "tytocare", "tytocare.com"),
        ("Healthy.io", "healthyio", "healthy.io"),
        ("K Health", "khealth", "khealth.com"),
    ],
    "automotive": [
        ("Mobileye", "mobileye", "mobileye.com"),
        ("Innoviz", "innoviz", "innoviz-tech.com"),
        ("Arbe Robotics", "arbe", "arbe-robotics.com"),
        ("Valens", "valens", "valens.com"),
        ("Autotalks", "autotalks", "autotalks.com"),
        ("Cognata", "cognata", "cognata.com"),
        ("Foretellix", "foretellix", "foretellix.com"),
        ("Vayyar", "vayyar", "vayyar.com"),
        ("TriEye", "trieye", "trieye.tech"),
        ("Adasky", "adasky", "adasky.com"),
        ("Otonomo", "otonomo", "otonomo.io"),
        ("Sibros", "sibros", "sibros.tech"),
        ("Mobility Insights", "mobilityinsights", "mobilityinsights.io"),
        ("Autobrains", "autobrains", "autobrains.ai"),
        ("Cognata", "cognata", "cognata.com"),
        ("Foretellix", "foretellix", "foretellix.com"),
        ("TriEye", "trieye", "trieye.tech"),
        ("Vayyar", "vayyar", "vayyar.com"),
        ("Innoviz", "innoviz", "innoviz-tech.com"),
        ("Mobileye", "mobileye", "mobileye.com"),
        ("Arbe Robotics", "arbe", "arbe-robotics.com"),
    ],
    "semiconductors": [
        ("Valens", "valens", "valens.com"),
        ("Autotalks", "autotalks", "autotalks.com"),
        ("DSP Group", "dspgroup", "dspg.com"),
        ("Ceva", "ceva", "ceva-dsp.com"),
        ("Tower Semiconductor", "towersemi", "towersemi.com"),
        ("Nova", "nova", "novameasuring.com"),
        ("KLA Israel", "klaisrael", "kla.com"),
        ("Applied Materials Israel", "appliedmaterials", "appliedmaterials.com"),
        ("Intel Israel", "intel", "intel.com"),
        ("NVIDIA Israel", "nvidia", "nvidia.com"),
        ("Amazon Web Services Israel", "aws", "amazon.com"),
        ("Google Israel", "google", "google.com"),
        ("Microsoft Israel", "microsoft", "microsoft.com"),
        ("Meta Israel", "meta", "meta.com"),
        ("Apple Israel", "apple", "apple.com"),
        ("IBM Israel", "ibm", "ibm.com"),
        ("Red Hat Israel", "redhat", "redhat.com"),
        ("VMware Israel", "vmware", "vmware.com"),
        ("Dell Technologies Israel", "dell", "delltechnologies.com"),
        ("HP Israel", "hp", "hp.com"),
        ("Lenovo Israel", "lenovo", "lenovo.com"),
    ],
    "data_infra": [
        ("Sisense", "sisense", "sisense.com"),
        ("Panoply", "panoply", "panoply.io"),
        ("Incorta", "incorta", "incorta.com"),
        ("Qubole", "qubole", "qubole.com"),
        ("DataBricks Israel", "databricks", "databricks.com"),
        ("Snowflake Israel", "snowflake", "snowflake.com"),
        ("MongoDB Israel", "mongodb", "mongodb.com"),
        ("Redis Israel", "redis", "redis.com"),
        ("Elastic Israel", "elastic", "elastic.co"),
        ("Confluent Israel", "confluent", "confluent.io"),
        ("HashiCorp Israel", "hashicorp", "hashicorp.com"),
        ("GitLab Israel", "gitlab", "gitlab.com"),
        ("GitHub Israel", "github", "github.com"),
        ("Atlassian Israel", "atlassian", "atlassian.com"),
        ("JFrog", "jfrog", "jfrog.com"),
        ("Snyk", "snyk", "snyk.io"),
        ("Aqua Security", "aqua-security", "aquasec.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("WhiteSource", "whitesource", "whitesourcesoftware.com"),
        ("SonarSource", "sonarsource", "sonarsource.com"),
        ("Veracode", "veracode", "veracode.com"),
        ("Contrast Security", "contrastsecurity", "contrastsecurity.com"),
        ("ShiftLeft", "shiftleft", "shiftleft.io"),
        ("OX Security", "oxsecurity", "ox.security"),
        ("Apiiro", "apiiro", "apiiro.com"),
        ("Bridgecrew", "bridgecrew", "bridgecrew.io"),
        ("Ermetic", "ermetic", "ermetic.com"),
        ("Orca Security", "orcasecurity", "orca.security"),
        ("Wiz", "wiz", "wiz.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Armis", "armis", "armis.com"),
        ("SentinelOne", "sentinelone", "sentinelone.com"),
        ("CyberArk", "cyberark", "cyberark.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("IronSource", "ironsource", "ironsrc.com"),
        ("Gong", "gong", "gong.io"),
        ("Snyk", "snyk", "snyk.io"),
        ("Lemonade", "lemonade", "lemonade.com"),
        ("Fiverr", "fiverr", "fiverr.com"),
    ],
    "quantum": [
        ("Classiq", "classiq", "classiq.io"),
        ("Quantum Machines", "quantummachines", "quantum-machines.co"),
        ("Qedma", "qedma", "qedma.io"),
        ("QuantLR", "quantlr", "quantlr.com"),
    ],
    "space": [
        ("SpaceIL", "spaceil", "spaceil.com"),
        ("ISA", "isa", "isa.org.il"),
        ("ImageSat", "imagesat", "imagesatintl.com"),
        ("NSLComm", "nslcomm", "nslcomm.com"),
        ("Ramon Space", "ramonspace", "ramon.space"),
        ("SpacePharma", "spacepharma", "spacepharma.com"),
        ("Helios", "helios", "helios.io"),
        ("Astroscale", "astroscale", "astroscale.com"),
    ],
    "agritech": [
        ("Netafim", "netafim", "netafim.com"),
        ("Phytech", "phytech", "phytech.com"),
        ("CropX", "cropx", "cropx.com"),
        ("Taranis", "taranis", "taranis.com"),
        ("Prospera", "prospera", "prospera.ag"),
        ("Treetoscope", "treetoscope", "treetoscope.com"),
        ("SupPlant", "supplant", "supplant.com"),
        ("Saturas", "saturas", "saturas.io"),
        ("Manna", "manna", "manna-irrigation.com"),
        ("N-Drip", "ndrip", "n-drip.com"),
    ],
    "watertech": [
        ("Mekorot", "mekorot", "mekorot.co.il"),
        ("IDE", "ide", "ide-tech.com"),
        ("TaKaDu", "takadu", "takadu.com"),
        ("Watergen", "watergen", "watergen.com"),
        ("HydroSpin", "hydrospin", "hydrospin.com"),
    ],
    "foodtech": [
        ("Aleph Farms", "alephfarms", "aleph-farms.com"),
        ("Redefine Meat", "redefinemeat", "redefinemeat.com"),
        ("Future Meat", "futuremeat", "future-meat.com"),
        ("Impossible Foods Israel", "impossible", "impossiblefoods.com"),
        ("Remilk", "remilk", "remilk.com"),
        ("Wilk", "wilk", "wilk.co.il"),
        ("BioMilk", "biomilk", "biomilk.co.il"),
        ("Yo Egg", "yoegg", "yo-egg.com"),
        ("Eggmented Reality", "eggmented", "eggmented.com"),
        ("SavorEat", "savoreat", "savoreat.com"),
    ],
    "climatetech": [
        ("Brenmiller", "brenmiller", "brenmiller.com"),
        ("H2Pro", "h2pro", "h2pro.io"),
        ("GenCell", "gencell", "gencellenergy.com"),
        ("Augwind", "augwind", "augwind.com"),
        ("SolarEdge", "solaredge", "solaredge.com"),
        ("Enlight", "enlight", "enlight-renewable.com"),
        ("Electreon", "electreon", "electreon.com"),
        ("StoreDot", "storedot", "storedot.com"),
        ("Addionics", "addionics", "addionics.com"),
    ],
    "construction": [
        ("Katerra", "katerra", "katerra.com"),
        ("Veev", "veev", "veev.io"),
        ("ICON", "icon", "iconbuild.com"),
        ("Mighty Buildings", "mightybuildings", "mightybuildings.com"),
    ],
    "logistics": [
        ("Freightos", "freightos", "freightos.com"),
        ("Windward", "windward", "windward.ai"),
        ("Orca AI", "orcaai", "orca-ai.com"),
        ("DockTech", "docktech", "docktech.io"),
    ],
    "edtech": [
        ("CodeMonkey", "codemonkey", "codemonkey.com"),
        ("Matific", "matific", "matific.com"),
        ("JoyTunes", "joytunes", "joytunes.com"),
        ("Simplilearn", "simplilearn", "simplilearn.com"),
    ],
    "proptech": [
        ("Guesty", "guesty", "guesty.com"),
        ("Veev", "veev", "veev.io"),
        ("Localize", "localize", "localize.city"),
        ("Skyline AI", "skylineai", "skyline.ai"),
    ],
    "retailtech": [
        ("Trigo", "trigo", "trigo.ai"),
        ("WalkOut", "walkout", "walkout.ai"),
        ("AiFi", "aifi", "aifi.io"),
        ("Grabango", "grabango", "grabango.com"),
    ],
    "insurtech": [
        ("Lemonade", "lemonade", "lemonade.com"),
        ("Hippo", "hippo", "hippo.com"),
        ("Wefox", "wefox", "wefox.com"),
        ("Next Insurance", "next-insurance", "nextinsurance.com"),
        ("Atidot", "atidot", "atidot.com"),
        ("Sproutt", "sproutt", "sproutt.com"),
        ("Best Doctors", "bestdoctors", "bestdoctors.com"),
    ],
    "legaltech": [
        ("LawGeex", "lawgeex", "lawgeex.com"),
        ("Darrow", "darrow", "darrow.ai"),
        ("LegalUp", "legalup", "legalup.com"),
    ],
    "biotech": [
        ("Immunai", "immunai", "immunai.com"),
        ("CytoReason", "cytroreason", "cytroreason.com"),
        ("K Health", "khealth", "khealth.com"),
        ("Healthy.io", "healthyio", "healthy.io"),
        ("TytoCare", "tytocare", "tytocare.com"),
        ("Antidote Health", "antidotehealth", "antidote.health"),
        ("Sweetch", "sweetch", "sweetch.com"),
        ("Laguna Health", "lagunahealth", "lagunahealth.com"),
        ("Belong.Life", "belonglife", "belong.life"),
        ("DayTwo", "daytwo", "daytwo.com"),
        ("MyHeritage", "myheritage", "myheritage.com"),
        ("GeneDx", "genedx", "genedx.com"),
        ("NuvoAir", "nuvoair", "nuvoair.com"),
        ("BrainQ", "brainq", "brainq.co"),
        ("Neura", "neura", "neura.com"),
        ("EarlySense", "earlysense", "earlysense.com"),
        ("Biobeat", "biobeat", "biobeat.com"),
        ("Nanit", "nanit", "nanit.com"),
        ("Inui Health", "inuihealth", "inuihealth.com"),
    ],
    "israeli_unicorns": [
        ("Wix", "wix", "wix.com"),
        ("Monday.com", "monday", "monday.com"),
        ("WalkMe", "walkme", "walkme.com"),
        ("JFrog", "jfrog", "jfrog.com"),
        ("Similarweb", "similarweb", "similarweb.com"),
        ("AppsFlyer", "appsflyer", "appsflyer.com"),
        ("Riskified", "riskified", "riskified.com"),
        ("FundGuard", "fundguard", "fundguard.com"),
        ("Hippo", "hippo", "hippo.com"),
        ("Wefox", "wefox", "wefox.com"),
        ("Lightricks", "lightricks", "lightricks.com"),
        ("Playtika", "playtika", "playtika.com"),
        ("Plarium", "plarium", "plarium.com"),
        ("Moon Active", "moonactive", "moonactive.com"),
        ("Playstudios", "playstudios", "playstudios.com"),
        ("SciPlay", "sciplay", "sciplay.com"),
        ("CrazyLabs", "crazylabs", "crazylabs.com"),
        ("Ilyon", "ilyon", "ilyon.net"),
        ("Playgendary", "playgendary", "playgendary.com"),
        ("Sayollo", "sayollo", "sayollo.com"),
        ("Overwolf", "overwolf", "overwolf.com"),
        ("Fiverr", "fiverr", "fiverr.com"),
        ("IronSource", "ironsource", "ironsrc.com"),
        ("Gong", "gong", "gong.io"),
        ("Snyk", "snyk", "snyk.io"),
        ("Lemonade", "lemonade", "lemonade.com"),
        ("Next Insurance", "next-insurance", "nextinsurance.com"),
        ("Hippo", "hippo", "hippo.com"),
        ("Wefox", "wefox", "wefox.com"),
        ("FundGuard", "fundguard", "fundguard.com"),
        ("Melio", "melio", "melio.com"),
        ("Pagaya", "pagaya", "pagaya.com"),
        ("Payoneer", "payoneer", "payoneer.com"),
        ("BlueVine", "bluevine", "bluevine.com"),
        ("Kabbage", "kabbage", "kabbage.com"),
        ("Nayax", "nayax", "nayax.com"),
        ("Bit2C", "bit2c", "bit2c.co.il"),
        ("CoinMama", "coinmama", "coinmama.com"),
        ("Simplex", "simplex", "simplex.com"),
        ("MoonPay", "moonpay", "moonpay.com"),
        ("Fireblocks", "fireblocks", "fireblocks.com"),
        ("Unbound Tech", "unboundtech", "unboundtech.com"),
        ("ZenGo", "zengo", "zengo.com"),
        ("StarkWare", "starkware", "starkware.co"),
        ("Matter Labs", "matterlabs", "matterlabs.dev"),
        ("Immutable", "immutable", "immutable.com"),
        ("Polygon", "polygon", "polygon.technology"),
        ("StarkNet", "starknet", "starknet.io"),
        ("ZKSync", "zksync", "zksync.io"),
        ("Arbitrum", "arbitrum", "arbitrum.io"),
        ("Optimism", "optimism", "optimism.io"),
        ("Base", "base", "base.org"),
        ("Linea", "linea", "linea.build"),
        ("Scroll", "scroll", "scroll.io"),
        ("Taiko", "taiko", "taiko.xyz"),
        ("Mantle", "mantle", "mantle.xyz"),
        ("Mode", "mode", "mode.network"),
        ("Blast", "blast", "blast.io"),
        ("Metis", "metis", "metis.io"),
        ("Boba", "boba", "boba.network"),
        ("Ape", "ape", "apecoin.com"),
        ("Pepe", "pepe", "pepe.vip"),
        ("Floki", "floki", "floki.com"),
        ("Shiba", "shiba", "shibatoken.com"),
        ("Doge", "doge", "dogecoin.com"),
    ],
    "adtech_martech": [
        ("AppsFlyer", "appsflyer", "appsflyer.com"),
        ("Adjust", "adjust", "adjust.com"),
        ("Singular", "singular", "singular.net"),
        ("Branch", "branch", "branch.io"),
        ("Kochava", "kochava", "kochava.com"),
        ("Tenjin", "tenjin", "tenjin.io"),
        ("Airbridge", "airbridge", "airbridge.io"),
        ("Appsumer", "appsumer", "appsumer.com"),
        ("Bidalgo", "bidalgo", "bidalgo.com"),
        ("Fyber", "fyber", "fyber.com"),
        ("IronSource", "ironsource", "ironsrc.com"),
        ("Tapjoy", "tapjoy", "tapjoy.com"),
        ("Chartboost", "chartboost", "chartboost.com"),
        ("Vungle", "vungle", "vungle.com"),
        ("Unity Ads", "unityads", "unity.com"),
        ("AppLovin", "applovin", "applovin.com"),
        ("InMobi", "inmobi", "inmobi.com"),
        ("Mintegral", "mintegral", "mintegral.com"),
        ("Moloco", "moloco", "moloco.com"),
        ("Liftoff", "liftoff", "liftoff.io"),
        ("Remerge", "remerge", "remerge.io"),
        ("Jampp", "jampp", "jampp.com"),
        ("Smadex", "smadex", "smadex.com"),
        ("Adikteev", "adikteev", "adikteev.com"),
        ("YouAppi", "youappi", "youappi.com"),
        ("RevJet", "revjet", "revjet.com"),
        ("Smartly.io", "smartly", "smartly.io"),
        ("Kenshoo", "kenshoo", "kenshoo.com"),
        ("Marin Software", "marin", "marinsoftware.com"),
        ("MediaMath", "mediamath", "mediamath.com"),
        ("The Trade Desk", "tradedesk", "thetradedesk.com"),
        ("DV360", "dv360", "dv360.google.com"),
        ("Amazon DSP", "amazonds", "amazon.com"),
        ("Criteo", "criteo", "criteo.com"),
        ("Outbrain", "outbrain", "outbrain.com"),
        ("Taboola", "taboola", "taboola.com"),
        ("Mgid", "mgid", "mgid.com"),
        ("RevContent", "revcontent", "revcontent.com"),
        ("Content.ad", "contentad", "content.ad"),
        ("Earnify", "earnify", "earnify.com"),
        ("Polar", "polar", "polar.com"),
        ("AdYouLike", "adyoulike", "adyoulike.com"),
        ("Sharethrough", "sharethrough", "sharethrough.com"),
        ("Teads", "teads", "teads.com"),
        ("Unruly", "unruly", "unruly.co"),
        ("SpotX", "spotx", "spotx.com"),
        ("Tremor Video", "tremor", "tremorvideo.com"),
        ("Telaria", "telaria", "telaria.com"),
        ("Rubicon Project", "rubicon", "rubiconproject.com"),
        ("PubMatic", "pubmatic", "pubmatic.com"),
        ("OpenX", "openx", "openx.com"),
        ("Index Exchange", "indexexchange", "indexexchange.com"),
        ("Sovrn", "sovrn", "sovrn.com"),
        ("District M", "districtm", "districtm.com"),
        ("GumGum", "gumgum", "gumgum.com"),
        ("Eyeview", "eyeview", "eyeview.com"),
        ("Innovid", "innovid", "innovid.com"),
        ("Tremor Video", "tremor", "tremorvideo.com"),
        ("Virool", "virool", "virool.com"),
        ("Video Intelligence", "videointelligence", "vi.ai"),
        ("Vuble", "vuble", "vuble.com"),
        ("Undertone", "undertone", "undertone.com"),
        ("RhythmOne", "rhythmone", "rhythmone.com"),
        ("Specific Media", "specificmedia", "specificmedia.com"),
        ("Adform", "adform", "adform.com"),
        ("Smart AdServer", "smartadserver", "smartadserver.com"),
        ("Equativ", "equativ", "equativ.com"),
        ("Adserver.Online", "adserveronline", "adserver.online"),
        ("Epom", "epom", "epom.com"),
        ("AdGlare", "adglare", "adglare.com"),
        ("AdButler", "adbutler", "adbutler.com"),
        ("Kevel", "kevel", "kevel.co"),
        ("Broadstreet", "broadstreet", "broadstreetads.com"),
        ("AdPlugg", "adplugg", "adplugg.com"),
        ("Adzerk", "adzerk", "adzerk.com"),
    ],
    "hr_tech": [
        ("HiBob", "hibob", "hibob.com"),
        ("Papaya Global", "papayaglobal", "papayaglobal.com"),
        ("Deel", "deel", "deel.com"),
        ("Remote", "remote", "remote.com"),
        ("Oyster", "oyster", "oysterhr.com"),
        ("Velocity Global", "velocityglobal", "velocityglobal.com"),
        ("Globalization Partners", "globalizationpartners", "globalizationpartners.com"),
        ("Safeguard Global", "safeguardglobal", "safeguardglobal.com"),
        ("Elements Global Services", "elementsglobal", "elementsgroup.com"),
        ("Omnipresent", "omnipresent", "omnipresent.com"),
        ("Workday", "workday", "workday.com"),
        ("SAP SuccessFactors", "successfactors", "successfactors.com"),
        ("Oracle HCM", "oraclehcm", "oracle.com"),
        ("ADP", "adp", "adp.com"),
        ("Paycom", "paycom", "paycom.com"),
        ("Paylocity", "paylocity", "paylocity.com"),
        ("Rippling", "rippling", "rippling.com"),
        ("Gusto", "gusto", "gusto.com"),
        ("Zenefits", "zenefits", "zenefits.com"),
        ("Justworks", "justworks", "justworks.com"),
        ("TriNet", "trinet", "trinet.com"),
        ("Insperity", "insperity", "insperity.com"),
        ("PEO", "peo", "peo.com"),
        ("Namely", "namely", "namely.com"),
        ("BambooHR", "bamboohr", "bamboohr.com"),
        ("Greenhouse", "greenhouse", "greenhouse.io"),
        ("Lever", "lever", "lever.co"),
        ("Workable", "workable", "workable.com"),
        ("JazzHR", "jazzhr", "jazzhr.com"),
        ("Breezy HR", "breezy", "breezy.hr"),
        ("SmartRecruiters", "smartrecruiters", "smartrecruiters.com"),
        ("iCIMS", "icims", "icims.com"),
        ("Jobvite", "jobvite", "jobvite.com"),
    ],
    "devtools": [
        ("GitLab", "gitlab", "gitlab.com"),
        ("GitHub", "github", "github.com"),
        ("Bitbucket", "bitbucket", "bitbucket.org"),
        ("GitKraken", "gitkraken", "gitkraken.com"),
        ("Sourcegraph", "sourcegraph", "sourcegraph.com"),
        ("CodeClimate", "codeclimate", "codeclimate.com"),
        ("SonarCloud", "sonarcloud", "sonarcloud.io"),
        ("Codecov", "codecov", "codecov.io"),
        ("Coveralls", "coveralls", "coveralls.io"),
        ("CodeScene", "codescene", "codescene.io"),
        ("Pluralsight", "pluralsight", "pluralsight.com"),
        ("CodeSignal", "codesignal", "codesignal.com"),
        ("HackerRank", "hackerrank", "hackerrank.com"),
        ("Codility", "codility", "codility.com"),
        ("LeetCode", "leetcode", "leetcode.com"),
    ],
    "gaming": [
        ("Playtika", "playtika", "playtika.com"),
        ("Plarium", "plarium", "plarium.com"),
        ("Moon Active", "moonactive", "moonactive.com"),
        ("Playstudios", "playstudios", "playstudios.com"),
        ("SciPlay", "sciplay", "sciplay.com"),
        ("CrazyLabs", "crazylabs", "crazylabs.com"),
        ("Ilyon", "ilyon", "ilyon.net"),
        ("Playgendary", "playgendary", "playgendary.com"),
        ("Sayollo", "sayollo", "sayollo.com"),
        ("Overwolf", "overwolf", "overwolf.com"),
    ],

def build() -> List[Dict]:
    company_map: Dict[str, Dict] = {}
    
    # Add working companies first
    for name, slug, domain, providers in working:
        slug_lower = slug.lower()
        if slug_lower not in company_map:
            company_map[slug_lower] = {"name": name, "slug": slug, "domain": domain, "providers": providers}
        else:
            for p in providers:
                if p not in company_map[slug_lower]["providers"]:
                    company_map[slug_lower]["providers"].append(p)
    
    # Add all additional companies
    for category, companies in additional.items():
        for name, slug, domain in companies:
            slug_lower = slug.lower()
            providers = provider_overrides.get(slug_lower, ["greenhouse"])
            if slug_lower not in company_map:
                company_map[slug_lower] = {"name": name, "slug": slug, "domain": domain, "providers": providers}
            else:
                for p in providers:
                    if p not in company_map[slug_lower]["providers"]:
                        company_map[slug_lower]["providers"].append(p)
    
    # Apply provider overrides
    for slug, providers in provider_overrides.items():
        slug_lower = slug.lower()
        if slug_lower in company_map:
            company_map[slug_lower]["providers"] = providers
    
    final = list(company_map.values())
    final.sort(key=lambda x: x["name"].lower())
    return final

if __name__ == "__main__":
    final = build()
    print(f"Total: {len(final)}")
    
    providers = {}
    for c in final:
        for p in c.get("providers", []):
            providers[p] = providers.get(p, 0) + 1
    print(f"Providers: {providers}")
    
    output = {
        "_comment": "Israeli tech companies that publish jobs on a public ATS. Each provider is a documented unauthenticated JSON API (no key, no login, no HTML scraping), so these rows are the employer's own postings with full descriptions. Add a company by probing its ATS slug: python3 agents/scan_jobs.py --ats-probe <slug>. Only providers returning >0 jobs are listed; the scanner skips the rest. `slug` is the ATS board identifier, not always the domain.",
        "companies": final
    }
    
    with open("agents/config/ats-companies.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    
    print(f"Written {len(final)} companies")