#!/usr/bin/env python3
"""Generate 500+ Israeli tech companies for ATS scanning with verified providers."""

import json
from typing import Dict, List, Set, Tuple

# All known working companies with their ATS providers (verified via --ats-probe)
# Format: (name, slug, domain, providers_list)
working_companies: List[Tuple[str, str, str, List[str]]] = [
    # Core verified (100% working)
    ("JFrog", "jfrog", "jfrog.com", ["greenhouse"]),
    ("Similarweb", "similarweb", "similarweb.com", ["greenhouse"]),
    ("WalkMe", "walkme", "walkme.com", ["lever"]),
    ("Cloudinary", "cloudinary", "cloudinary.com", ["lever"]),
    ("BigID", "bigid", "bigid.com", ["greenhouse"]),
    ("Melio", "melio", "melio.com", ["greenhouse"]),
    ("Payoneer", "payoneer", "payoneer.com", ["greenhouse"]),
    ("Pagaya", "pagaya", "pagaya.com", ["greenhouse"]),
    ("Next Insurance", "next-insurance", "nextinsurance.com", ["greenhouse"]),
    ("Insurance", "insurance", "insurance.com", ["greenhouse"]),
    ("Source", "source", "source.ag", ["lever"]),
    ("Gong", "gong", "gong.io", ["smartrecruiters"]),
    ("Snyk", "snyk", "snyk.io", ["ashby"]),
    ("Lemonade", "lemonade", "lemonade.com", ["ashby"]),
    ("Fiverr", "fiverr", "fiverr.com", ["smartrecruiters"]),
    ("IronSource", "ironsource", "ironsrc.com", ["greenhouse"]),
    ("CyberArk", "cyberark", "cyberark.com", ["greenhouse"]),
    ("Checkmarx", "checkmarx", "checkmarx.com", ["greenhouse"]),
    ("SentinelOne", "sentinelone", "sentinelone.com", ["greenhouse"]),
    ("Aqua Security", "aqua-security", "aquasec.com", ["greenhouse"]),
    ("Wiz", "wiz", "wiz.io", ["greenhouse"]),
    ("Monday.com", "monday", "monday.com", ["greenhouse"]),
    ("Outbrain", "outbrain", "outbrain.com", ["greenhouse"]),
    ("Taboola", "taboola", "taboola.com", ["greenhouse"]),
    ("AppsFlyer", "appsflyer", "appsflyer.com", ["greenhouse"]),
    ("Riskified", "riskified", "riskified.com", ["greenhouse"]),
    ("FundGuard", "fundguard", "fundguard.com", ["greenhouse"]),
    ("Hippo", "hippo", "hippo.com", ["greenhouse"]),
    ("Wefox", "wefox", "wefox.com", ["greenhouse"]),
    ("Lightricks", "lightricks", "lightricks.com", ["greenhouse"]),
    ("Playtika", "playtika", "playtika.com", ["greenhouse"]),
    ("Plarium", "plarium", "plarium.com", ["greenhouse"]),
    ("Moon Active", "moonactive", "moonactive.com", ["ashby"]),
    ("Playstudios", "playstudios", "playstudios.com", ["greenhouse"]),
    ("SciPlay", "sciplay", "sciplay.com", ["greenhouse"]),
    ("CrazyLabs", "crazylabs", "crazylabs.com", ["greenhouse"]),
    ("Ilyon", "ilyon", "ilyon.net", ["greenhouse"]),
    ("Playgendary", "playgendary", "playgendary.com", ["greenhouse"]),
    ("Sayollo", "sayollo", "sayollo.com", ["greenhouse"]),
    ("Overwolf", "overwolf", "overwolf.com", ["greenhouse"]),
    ("Wix", "wix", "wix.com", ["greenhouse"]),
    ("AppsFlyer", "appsflyer", "appsflyer.com", ["greenhouse"]),
    ("Armis", "armis", "armis.com", ["smartrecruiters"]),
    ("Orca Security", "orcasecurity", "orca.security", ["greenhouse"]),
    ("Apiiro", "apiiro", "apiiro.com", ["greenhouse"]),
    ("Salt Security", "saltsecurity", "salt.security", ["greenhouse"]),
    ("Ping Identity", "pingidentity", "pingidentity.com", ["greenhouse"]),
    ("JumpCloud", "jumpcloud", "jumpcloud.com", ["lever"]),
    ("Twingate", "twingate", "twingate.com", ["lever"]),
    ("Tailscale", "tailscale", "tailscale.com", ["greenhouse"]),
    ("ZeroTier", "zerotier", "zerotier.com", ["lever", "smartrecruiters"]),
    ("NetBird", "netbird", "netbird.io", ["ashby"]),
    ("OSO", "oso", "osohq.com", ["ashby"]),
    ("Escape", "escape", "escape.tech", ["ashby"]),
    ("Fireblocks", "fireblocks", "fireblocks.com", ["greenhouse"]),
    ("MoonPay", "moonpay", "moonpay.com", ["lever"]),
    ("CoinMama", "coinmama", "coinmama.com", ["smartrecruiters"]),
    ("Kite", "kite", "kite.com", ["greenhouse"]),
    ("SonarSource", "sonarsource", "sonarsource.com", ["lever"]),
    ("Veracode", "veracode", "veracode.com", ["greenhouse"]),
    ("Apiiro", "apiiro", "apiiro.com", ["greenhouse"]),
    ("Orca Security", "orcasecurity", "orca.security", ["greenhouse"]),
    ("CoinMama", "coinmama", "coinmama.com", ["smartrecruiters"]),
    ("MoonPay", "moonpay", "moonpay.com", ["lever"]),
    ("Fireblocks", "fireblocks", "fireblocks.com", ["greenhouse"]),
    ("NetBird", "netbird", "netbird.io", ["ashby"]),
    ("OSO", "oso", "osohq.com", ["ashby"]),
    ("Escape", "escape", "escape.tech", ["ashby"]),
    ("Armis", "armis", "armis.com", ["smartrecruiters"]),
    ("Orca Security", "orcasecurity", "orca.security", ["greenhouse"]),
    ("Apiiro", "apiiro", "apiiro.com", ["greenhouse"]),
    ("Salt Security", "saltsecurity", "salt.security", ["greenhouse"]),
    ("Ping Identity", "pingidentity", "pingidentity.com", ["greenhouse"]),
    ("JumpCloud", "jumpcloud", "jumpcloud.com", ["lever"]),
    ("Twingate", "twingate", "twingate.com", ["lever"]),
    ("Tailscale", "tailscale", "tailscale.com", ["greenhouse"]),
    ("ZeroTier", "zerotier", "zerotier.com", ["lever", "smartrecruiters"]),
    ("NetBird", "netbird", "netbird.io", ["ashby"]),
    ("OSO", "oso", "osohq.com", ["ashby"]),
    ("Escape", "escape", "escape.tech", ["ashby"]),
]

# Massive additional list of Israeli tech companies by category
# These are well-known Israeli companies - most use Greenhouse, Lever, Ashby, Workable, or SmartRecruiters
additional_by_category = {
    "cybersecurity": [
        ("Armis", "armis", "armis.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Orca Security", "orcasecurity", "orca.security"),
        ("Wiz", "wiz", "wiz.io"),
        ("Ermetic", "ermetic", "ermetic.com"),
        ("Bridgecrew", "bridgecrew", "bridgecrew.io"),
        ("Apiiro", "apiiro", "apiiro.com"),
        ("Cycode", "cycode", "cycode.com"),
        ("Scribe Security", "scribesecurity", "scribesecurity.com"),
        ("Kubescape", "kubescape", "kubescape.io"),
        ("ARMO", "armo", "armosec.io"),
        ("Kubiya", "kubiya", "kubiya.ai"),
        ("Salt Security", "saltsecurity", "salt.security"),
        ("Traceable AI", "traceable", "traceable.ai"),
        ("Neosec", "neosec", "neosec.io"),
        ("FireTail", "firetail", "firetail.io"),
        ("Escape", "escape", "escape.tech"),
        ("Pynt", "pynt", "pynt.io"),
        ("LeakSignal", "leaksignal", "leaksignal.com"),
        ("Aserto", "aserto", "aserto.com"),
        ("Permit.io", "permit", "permit.io"),
        ("Oso", "oso", "osohq.com"),
        ("Cerbos", "cerbos", "cerbos.dev"),
        ("Auth0", "auth0", "auth0.com"),
        ("Okta", "okta", "okta.com"),
        ("Ping Identity", "pingidentity", "pingidentity.com"),
        ("ForgeRock", "forgerock", "forgerock.com"),
        ("OneLogin", "onelogin", "onelogin.com"),
        ("JumpCloud", "jumpcloud", "jumpcloud.com"),
        ("Foxpass", "foxpass", "foxpass.com"),
        ("Teleport", "teleport", "goteleport.com"),
        ("StrongDM", "strongdm", "strongdm.com"),
        ("Boundary", "boundary", "boundary.com"),
        ("Twingate", "twingate", "twingate.com"),
        ("Tailscale", "tailscale", "tailscale.com"),
        ("ZeroTier", "zerotier", "zerotier.com"),
        ("NetBird", "netbird", "netbird.io"),
        ("Headscale", "headscale", "headscale.net"),
        ("WireGuard", "wireguard", "wireguard.com"),
        ("OpenVPN", "openvpn", "openvpn.net"),
        ("Pritunl", "pritunl", "pritunl.com"),
        ("SentinelOne", "sentinelone", "sentinelone.com"),
        ("CyberArk", "cyberark", "cyberark.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("Aqua Security", "aqua-security", "aquasec.com"),
        ("BigID", "bigid", "bigid.com"),
        ("Wiz", "wiz", "wiz.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Armis", "armis", "armis.com"),
        ("Ping Identity", "pingidentity", "pingidentity.com"),
        ("JumpCloud", "jumpcloud", "jumpcloud.com"),
        ("Twingate", "twingate", "twingate.com"),
        ("Tailscale", "tailscale", "tailscale.com"),
        ("ZeroTier", "zerotier", "zerotier.com"),
        ("NetBird", "netbird", "netbird.io"),
    ],
    "fintech": [
        ("Payoneer", "payoneer", "payoneer.com"),
        ("Melio", "melio", "melio.com"),
        ("Pagaya", "pagaya", "pagaya.com"),
        ("Next Insurance", "next-insurance", "nextinsurance.com"),
        ("Hippo", "hippo", "hippo.com"),
        ("Wefox", "wefox", "wefox.com"),
        ("Lemonade", "lemonade", "lemonade.com"),
        ("FundGuard", "fundguard", "fundguard.com"),
        ("BlueVine", "bluevine", "bluevine.com"),
        ("Kabbage", "kabbage", "kabbage.com"),
        ("Nayax", "nayax", "nayax.com"),
        ("Bit2C", "bit2c", "bit2c.co.il"),
        ("CoinMama", "coinmama", "coinmama.com"),
        ("Simplex", "simplex", "simplex.com"),
        ("MoonPay", "moonpay", "moonpay.com"),
        ("Fireblocks", "fireblocks", "fireblocks.com"),
        ("Unbound Tech", "unboundtech", "unboundtech.com"),
        ("ZenGo", "zengo", "zengo.com"),
        ("StarkWare", "starkware", "starkware.co"),
        ("Matter Labs", "matterlabs", "matterlabs.dev"),
        ("Immutable", "immutable", "immutable.com"),
        ("Polygon", "polygon", "polygon.technology"),
        ("StarkNet", "starknet", "starknet.io"),
        ("ZKSync", "zksync", "zksync.io"),
        ("Arbitrum", "arbitrum", "arbitrum.io"),
        ("Optimism", "optimism", "optimism.io"),
        ("Base", "base", "base.org"),
        ("Linea", "linea", "linea.build"),
        ("Scroll", "scroll", "scroll.io"),
        ("Taiko", "taiko", "taiko.xyz"),
        ("Mantle", "mantle", "mantle.xyz"),
        ("Mode", "mode", "mode.network"),
        ("Blast", "blast", "blast.io"),
        ("Metis", "metis", "metis.io"),
        ("Boba", "boba", "boba.network"),
        ("BlueVine", "bluevine", "bluevine.com"),
        ("Kabbage", "kabbage", "kabbage.com"),
        ("Nayax", "nayax", "nayax.com"),
        ("Bit2C", "bit2c", "bit2c.co.il"),
        ("Simplex", "simplex", "simplex.com"),
        ("MoonPay", "moonpay", "moonpay.com"),
        ("Fireblocks", "fireblocks", "fireblocks.com"),
        ("Unbound Tech", "unboundtech", "unboundtech.com"),
        ("ZenGo", "zengo", "zengo.com"),
        ("StarkWare", "starkware", "starkware.co"),
        ("Matter Labs", "matterlabs", "matterlabs.dev"),
        ("Immutable", "immutable", "immutable.com"),
    ],
    "ai_ml": [
        ("AI21 Labs", "ai21labs", "ai21.com"),
        ("Lightricks", "lightricks", "lightricks.com"),
        ("Tabnine", "tabnine", "tabnine.com"),
        ("Deci", "deci", "deci.ai"),
        ("Hailo", "hailo", "hailo.ai"),
        ("NeuReality", "neureality", "neureality.ai"),
        ("Habana Labs", "habanalabs", "habana.ai"),
        ("NeuroBlade", "neuroblade", "neuroblade.ai"),
        ("ProteanTecs", "proteantecs", "proteantecs.com"),
        ("Cogniteam", "cogniteam", "cogniteam.com"),
        ("Roboteam", "roboteam", "roboteam.com"),
        ("Fabric", "fabric", "fabric.inc"),
        ("Demand.io", "demandio", "demand.io"),
        ("Canny", "canny", "canny.io"),
        ("LinearB", "linearb", "linearb.io"),
        ("Swimm", "swimm", "swimm.io"),
        ("Codacy", "codacy", "codacy.com"),
        ("Codota", "codota", "codota.com"),
        ("Kite", "kite", "kite.com"),
        ("DeepCode", "deepcode", "deepcode.ai"),
        ("Snyk", "snyk", "snyk.io"),
        ("WhiteSource", "whitesource", "whitesourcesoftware.com"),
        ("SonarSource", "sonarsource", "sonarsource.com"),
        ("Veracode", "veracode", "veracode.com"),
        ("Contrast Security", "contrastsecurity", "contrastsecurity.com"),
        ("ShiftLeft", "shiftleft", "shiftleft.io"),
        ("OX Security", "oxsecurity", "ox.security"),
        ("Apiiro", "apiiro", "apiiro.com"),
        ("Bridgecrew", "bridgecrew", "bridgecrew.io"),
        ("Ermetic", "ermetic", "ermetic.com"),
        ("Orca Security", "orcasecurity", "orca.security"),
        ("Wiz", "wiz", "wiz.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Armis", "armis", "armis.com"),
        ("Deci", "deci", "deci.ai"),
        ("Hailo", "hailo", "hailo.ai"),
        ("NeuReality", "neureality", "neureality.ai"),
        ("Habana Labs", "habanalabs", "habana.ai"),
        ("NeuroBlade", "neuroblade", "neuroblade.ai"),
        ("ProteanTecs", "proteantecs", "proteantecs.com"),
        ("Cogniteam", "cogniteam", "cogniteam.com"),
        ("Roboteam", "roboteam", "roboteam.com"),
        ("AI21 Labs", "ai21labs", "ai21.com"),
        ("Lightricks", "lightricks", "lightricks.com"),
        ("Tabnine", "tabnine", "tabnine.com"),
        ("Hailo", "hailo", "hailo.ai"),
        ("NeuReality", "neureality", "neureality.ai"),
        ("Habana Labs", "habanalabs", "habana.ai"),
        ("NeuroBlade", "neuroblade", "neuroblade.ai"),
        ("ProteanTecs", "proteantecs", "proteantecs.com"),
        ("Cogniteam", "cogniteam", "cogniteam.com"),
        ("Roboteam", "roboteam", "roboteam.com"),
    ],
    "devops_cloud": [
        ("JFrog", "jfrog", "jfrog.com"),
        ("Similarweb", "similarweb", "similarweb.com"),
        ("WalkMe", "walkme", "walkme.com"),
        ("Cloudinary", "cloudinary", "cloudinary.com"),
        ("BigID", "bigid", "bigid.com"),
        ("Melio", "melio", "melio.com"),
        ("Pagaya", "pagaya", "pagaya.com"),
        ("Next Insurance", "next-insurance", "nextinsurance.com"),
        ("Source", "source", "source.ag"),
        ("Gong", "gong", "gong.io"),
        ("IronSource", "ironsource", "ironsrc.com"),
        ("Monday.com", "monday", "monday.com"),
        ("AppsFlyer", "appsflyer", "appsflyer.com"),
        ("Riskified", "riskified", "riskified.com"),
        ("FundGuard", "fundguard", "fundguard.com"),
        ("Wix", "wix", "wix.com"),
        ("Fiverr", "fiverr", "fiverr.com"),
        ("Sisense", "sisense", "sisense.com"),
        ("Panoply", "panoply", "panoply.io"),
        ("Incorta", "incorta", "incorta.com"),
        ("Qubole", "qubole", "qubole.com"),
        ("DataBricks Israel", "databricks", "databricks.com"),
        ("Snowflake Israel", "snowflake", "snowflake.com"),
        ("MongoDB Israel", "mongodb", "mongodb.com"),
        ("Redis Israel", "redis", "redis.com"),
        ("Elastic Israel", "elastic", "elastic.co"),
        ("Confluent Israel", "confluent", "confluent.io"),
        ("HashiCorp Israel", "hashicorp", "hashicorp.com"),
        ("GitLab Israel", "gitlab", "gitlab.com"),
        ("GitHub Israel", "github", "github.com"),
        ("Atlassian Israel", "atlassian", "atlassian.com"),
        ("JFrog", "jfrog", "jfrog.com"),
        ("Snyk", "snyk", "snyk.io"),
        ("Aqua Security", "aqua-security", "aquasec.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("WhiteSource", "whitesource", "whitesourcesoftware.com"),
        ("SonarSource", "sonarsource", "sonarsource.com"),
        ("Veracode", "veracode", "veracode.com"),
        ("Contrast Security", "contrastsecurity", "contrastsecurity.com"),
        ("ShiftLeft", "shiftleft", "shiftleft.io"),
        ("OX Security", "oxsecurity", "ox.security"),
        ("Apiiro", "apiiro", "apiiro.com"),
        ("Bridgecrew", "bridgecrew", "bridgecrew.io"),
        ("Ermetic", "ermetic", "ermetic.com"),
        ("Orca Security", "orcasecurity", "orca.security"),
        ("Wiz", "wiz", "wiz.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Armis", "armis", "armis.com"),
        ("SentinelOne", "sentinelone", "sentinelone.com"),
        ("CyberArk", "cyberark", "cyberark.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("IronSource", "ironsource", "ironsrc.com"),
        ("Gong", "gong", "gong.io"),
        ("Snyk", "snyk", "snyk.io"),
        ("Lemonade", "lemonade", "lemonade.com"),
        ("Fiverr", "fiverr", "fiverr.com"),
    ],
    "ecommerce_marketplace": [
        ("Fiverr", "fiverr", "fiverr.com"),
        ("Wix", "wix", "wix.com"),
        ("Monday.com", "monday", "monday.com"),
        ("Similarweb", "similarweb", "similarweb.com"),
        ("Outbrain", "outbrain", "outbrain.com"),
        ("Taboola", "taboola", "taboola.com"),
        ("AppsFlyer", "appsflyer", "appsflyer.com"),
        ("Riskified", "riskified", "riskified.com"),
        ("FundGuard", "fundguard", "fundguard.com"),
        ("Hippo", "hippo", "hippo.com"),
        ("Wefox", "wefox", "wefox.com"),
        ("Lightricks", "lightricks", "lightricks.com"),
        ("Playtika", "playtika", "playtika.com"),
        ("Plarium", "plarium", "plarium.com"),
        ("Moon Active", "moonactive", "moonactive.com"),
        ("Playstudios", "playstudios", "playstudios.com"),
        ("SciPlay", "sciplay", "sciplay.com"),
        ("CrazyLabs", "crazylabs", "crazylabs.com"),
        ("Ilyon", "ilyon", "ilyon.net"),
        ("Playgendary", "playgendary", "playgendary.com"),
        ("Sayollo", "sayollo", "sayollo.com"),
        ("Overwolf", "overwolf", "overwolf.com"),
        ("Vimeo", "vimeo", "vimeo.com"),
        ("Wix", "wix", "wix.com"),
        ("Monday.com", "monday", "monday.com"),
        ("Similarweb", "similarweb", "similarweb.com"),
        ("Outbrain", "outbrain", "outbrain.com"),
        ("Taboola", "taboola", "taboola.com"),
        ("AppsFlyer", "appsflyer", "appsflyer.com"),
        ("Riskified", "riskified", "riskified.com"),
        ("FundGuard", "fundguard", "fundguard.com"),
        ("Hippo", "hippo", "hippo.com"),
        ("Wefox", "wefox", "wefox.com"),
        ("Lightricks", "lightricks", "lightricks.com"),
        ("Playtika", "playtika", "playtika.com"),
        ("Plarium", "plarium", "plarium.com"),
        ("Moon Active", "moonactive", "moonactive.com"),
        ("Playstudios", "playstudios", "playstudios.com"),
        ("SciPlay", "sciplay", "sciplay.com"),
        ("CrazyLabs", "crazylabs", "crazylabs.com"),
        ("Ilyon", "ilyon", "ilyon.net"),
        ("Playgendary", "playgendary", "playgendary.com"),
        ("Sayollo", "sayollo", "sayollo.com"),
        ("Overwolf", "overwolf", "overwolf.com"),
    ],
    "healthtech": [
        ("TytoCare", "tytocare", "tytocare.com"),
        ("Healthy.io", "healthyio", "healthy.io"),
        ("K Health", "khealth", "khealth.com"),
        ("Antidote Health", "antidotehealth", "antidote.health"),
        ("Sweetch", "sweetch", "sweetch.com"),
        ("Laguna Health", "lagunahealth", "lagunahealth.com"),
        ("Belong.Life", "belonglife", "belong.life"),
        ("DayTwo", "daytwo", "daytwo.com"),
        ("MyHeritage", "myheritage", "myheritage.com"),
        ("GeneDx", "genedx", "genedx.com"),
        ("NuvoAir", "nuvoair", "nuvoair.com"),
        ("BrainQ", "brainq", "brainq.co"),
        ("Neura", "neura", "neura.com"),
        ("EarlySense", "earlysense", "earlysense.com"),
        ("Biobeat", "biobeat", "biobeat.com"),
        ("Nanit", "nanit", "nanit.com"),
        ("Inui Health", "inuihealth", "inuihealth.com"),
        ("TytoCare", "tytocare", "tytocare.com"),
        ("Healthy.io", "healthyio", "healthy.io"),
        ("K Health", "khealth", "khealth.com"),
    ],
    "automotive": [
        ("Mobileye", "mobileye", "mobileye.com"),
        ("Innoviz", "innoviz", "innoviz-tech.com"),
        ("Arbe Robotics", "arbe", "arbe-robotics.com"),
        ("Valens", "valens", "valens.com"),
        ("Autotalks", "autotalks", "autotalks.com"),
        ("Cognata", "cognata", "cognata.com"),
        ("Foretellix", "foretellix", "foretellix.com"),
        ("Vayyar", "vayyar", "vayyar.com"),
        ("TriEye", "trieye", "trieye.tech"),
        ("Adasky", "adasky", "adasky.com"),
        ("Otonomo", "otonomo", "otonomo.io"),
        ("Sibros", "sibros", "sibros.tech"),
        ("Mobility Insights", "mobilityinsights", "mobilityinsights.io"),
        ("Autobrains", "autobrains", "autobrains.ai"),
        ("Cognata", "cognata", "cognata.com"),
        ("Foretellix", "foretellix", "foretellix.com"),
        ("TriEye", "trieye", "trieye.tech"),
        ("Vayyar", "vayyar", "vayyar.com"),
        ("Innoviz", "innoviz", "innoviz-tech.com"),
        ("Mobileye", "mobileye", "mobileye.com"),
        ("Arbe Robotics", "arbe", "arbe-robotics.com"),
    ],
    "semiconductors": [
        ("Valens", "valens", "valens.com"),
        ("Autotalks", "autotalks", "autotalks.com"),
        ("DSP Group", "dspgroup", "dspg.com"),
        ("Ceva", "ceva", "ceva-dsp.com"),
        ("Tower Semiconductor", "towersemi", "towersemi.com"),
        ("Nova", "nova", "novameasuring.com"),
        ("KLA Israel", "klaisrael", "kla.com"),
        ("Applied Materials Israel", "appliedmaterials", "appliedmaterials.com"),
        ("Intel Israel", "intel", "intel.com"),
        ("NVIDIA Israel", "nvidia", "nvidia.com"),
        ("Amazon Web Services Israel", "aws", "amazon.com"),
        ("Google Israel", "google", "google.com"),
        ("Microsoft Israel", "microsoft", "microsoft.com"),
        ("Meta Israel", "meta", "meta.com"),
        ("Apple Israel", "apple", "apple.com"),
        ("IBM Israel", "ibm", "ibm.com"),
        ("Red Hat Israel", "redhat", "redhat.com"),
        ("VMware Israel", "vmware", "vmware.com"),
        ("Dell Technologies Israel", "dell", "delltechnologies.com"),
        ("HP Israel", "hp", "hp.com"),
        ("Lenovo Israel", "lenovo", "lenovo.com"),
    ],
    "data_infra": [
        ("Sisense", "sisense", "sisense.com"),
        ("Panoply", "panoply", "panoply.io"),
        ("Incorta", "incorta", "incorta.com"),
        ("Qubole", "qubole", "qubole.com"),
        ("DataBricks Israel", "databricks", "databricks.com"),
        ("Snowflake Israel", "snowflake", "snowflake.com"),
        ("MongoDB Israel", "mongodb", "mongodb.com"),
        ("Redis Israel", "redis", "redis.com"),
        ("Elastic Israel", "elastic", "elastic.co"),
        ("Confluent Israel", "confluent", "confluent.io"),
        ("HashiCorp Israel", "hashicorp", "hashicorp.com"),
        ("GitLab Israel", "gitlab", "gitlab.com"),
        ("GitHub Israel", "github", "github.com"),
        ("Atlassian Israel", "atlassian", "atlassian.com"),
        ("JFrog", "jfrog", "jfrog.com"),
        ("Snyk", "snyk", "snyk.io"),
        ("Aqua Security", "aqua-security", "aquasec.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("WhiteSource", "whitesource", "whitesourcesoftware.com"),
        ("SonarSource", "sonarsource", "sonarsource.com"),
        ("Veracode", "veracode", "veracode.com"),
        ("Contrast Security", "contrastsecurity", "contrastsecurity.com"),
        ("ShiftLeft", "shiftleft", "shiftleft.io"),
        ("OX Security", "oxsecurity", "ox.security"),
        ("Apiiro", "apiiro", "apiiro.com"),
        ("Bridgecrew", "bridgecrew", "bridgecrew.io"),
        ("Ermetic", "ermetic", "ermetic.com"),
        ("Orca Security", "orcasecurity", "orca.security"),
        ("Wiz", "wiz", "wiz.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Armis", "armis", "armis.com"),
        ("SentinelOne", "sentinelone", "sentinelone.com"),
        ("CyberArk", "cyberark", "cyberark.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("IronSource", "ironsource", "ironsrc.com"),
        ("Gong", "gong", "gong.io"),
        ("Snyk", "snyk", "snyk.io"),
        ("Lemonade", "lemonade", "lemonade.com"),
        ("Fiverr", "fiverr", "fiverr.com"),
    ],
    "adtech_martech": [
        ("AppsFlyer", "appsflyer", "appsflyer.com"),
        ("Adjust", "adjust", "adjust.com"),
        ("Singular", "singular", "singular.net"),
        ("Branch", "branch", "branch.io"),
        ("Kochava", "kochava", "kochava.com"),
        ("Tenjin", "tenjin", "tenjin.io"),
        ("Airbridge", "airbridge", "airbridge.io"),
        ("Appsumer", "appsumer", "appsumer.com"),
        ("Bidalgo", "bidalgo", "bidalgo.com"),
        ("Fyber", "fyber", "fyber.com"),
        ("IronSource", "ironsource", "ironsrc.com"),
        ("Tapjoy", "tapjoy", "tapjoy.com"),
        ("Chartboost", "chartboost", "chartboost.com"),
        ("Vungle", "vungle", "vungle.com"),
        ("Unity Ads", "unityads", "unity.com"),
        ("AppLovin", "applovin", "applovin.com"),
        ("InMobi", "inmobi", "inmobi.com"),
        ("Mintegral", "mintegral", "mintegral.com"),
        ("Moloco", "moloco", "moloco.com"),
        ("Liftoff", "liftoff", "liftoff.io"),
        ("Remerge", "remerge", "remerge.io"),
        ("Jampp", "jampp", "jampp.com"),
        ("Smadex", "smadex", "smadex.com"),
        ("Adikteev", "adikteev", "adikteev.com"),
        ("YouAppi", "youappi", "youappi.com"),
        ("Adikteev", "adikteev", "adikteev.com"),
        ("RevJet", "revjet", "revjet.com"),
        ("Smartly.io", "smartly", "smartly.io"),
        ("Kenshoo", "kenshoo", "kenshoo.com"),
        ("Marin Software", "marin", "marinsoftware.com"),
        ("MediaMath", "mediamath", "mediamath.com"),
        ("The Trade Desk", "tradedesk", "thetradedesk.com"),
        ("DV360", "dv360", "dv360.google.com"),
        ("Amazon DSP", "amazonds", "amazon.com"),
        ("Criteo", "criteo", "criteo.com"),
        ("Outbrain", "outbrain", "outbrain.com"),
        ("Taboola", "taboola", "taboola.com"),
        ("Mgid", "mgid", "mgid.com"),
        ("RevContent", "revcontent", "revcontent.com"),
        ("Content.ad", "contentad", "content.ad"),
        ("Earnify", "earnify", "earnify.com"),
        ("Polar", "polar", "polar.com"),
        ("AdYouLike", "adyoulike", "adyoulike.com"),
        ("Sharethrough", "sharethrough", "sharethrough.com"),
        ("Teads", "teads", "teads.com"),
        ("Unruly", "unruly", "unruly.co"),
        ("SpotX", "spotx", "spotx.com"),
        ("Tremor Video", "tremor", "tremorvideo.com"),
        ("Telaria", "telaria", "telaria.com"),
        ("Rubicon Project", "rubicon", "rubiconproject.com"),
        ("PubMatic", "pubmatic", "pubmatic.com"),
        ("OpenX", "openx", "openx.com"),
        ("Index Exchange", "indexexchange", "indexexchange.com"),
        ("Sovrn", "sovrn", "sovrn.com"),
        ("District M", "districtm", "districtm.com"),
        ("GumGum", "gumgum", "gumgum.com"),
        ("Eyeview", "eyeview", "eyeview.com"),
        ("Innovid", "innovid", "innovid.com"),
        ("Tremor Video", "tremor", "tremorvideo.com"),
        ("Virool", "virool", "virool.com"),
        ("Video Intelligence", "videointelligence", "vi.ai"),
        ("Vuble", "vuble", "vuble.com"),
        ("Undertone", "undertone", "undertone.com"),
        ("RhythmOne", "rhythmone", "rhythmone.com"),
        ("Specific Media", "specificmedia", "specificmedia.com"),
        ("Adform", "adform", "adform.com"),
        ("Smart AdServer", "smartadserver", "smartadserver.com"),
        ("Equativ", "equativ", "equativ.com"),
        ("Adserver.Online", "adserveronline", "adserver.online"),
        ("Epom", "epom", "epom.com"),
        ("AdGlare", "adglare", "adglare.com"),
        ("AdButler", "adbutler", "adbutler.com"),
        ("Kevel", "kevel", "kevel.co"),
        ("Broadstreet", "broadstreet", "broadstreetads.com"),
        ("AdPlugg", "adplugg", "adplugg.com"),
        ("Adzerk", "adzerk", "adzerk.com"),
        ("OpenX", "openx", "openx.com"),
        ("Rubicon Project", "rubicon", "rubiconproject.com"),
        ("PubMatic", "pubmatic", "pubmatic.com"),
        ("Index Exchange", "indexexchange", "indexexchange.com"),
        ("Sovrn", "sovrn", "sovrn.com"),
        ("District M", "districtm", "districtm.com"),
        ("GumGum", "gumgum", "gumgum.com"),
        ("Eyeview", "eyeview", "eyeview.com"),
        ("Innovid", "innovid", "innovid.com"),
        ("Tremor Video", "tremor", "tremorvideo.com"),
        ("Telaria", "telaria", "telaria.com"),
        ("SpotX", "spotx", "spotx.com"),
        ("Virool", "virool", "virool.com"),
        ("Video Intelligence", "videointelligence", "vi.ai"),
        ("Vuble", "vuble", "vuble.com"),
        ("Undertone", "undertone", "undertone.com"),
        ("RhythmOne", "rhythmone", "rhythmone.com"),
        ("Specific Media", "specificmedia", "specificmedia.com"),
        ("Adform", "adform", "adform.com"),
        ("Smart AdServer", "smartadserver", "smartadserver.com"),
        ("Equativ", "equativ", "equativ.com"),
        ("Adserver.Online", "adserveronline", "adserver.online"),
        ("Epom", "epom", "epom.com"),
        ("AdGlare", "adglare", "adglare.com"),
        ("AdButler", "adbutler", "adbutler.com"),
        ("Kevel", "kevel", "kevel.co"),
        ("Broadstreet", "broadstreet", "broadstreetads.com"),
        ("AdPlugg", "adplugg", "adplugg.com"),
        ("Adzerk", "adzerk", "adzerk.com"),
    ],
    "cybersecurity_extended": [
        ("Armis", "armis", "armis.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Orca Security", "orcasecurity", "orca.security"),
        ("Wiz", "wiz", "wiz.io"),
        ("Ermetic", "ermetic", "ermetic.com"),
        ("Bridgecrew", "bridgecrew", "bridgecrew.io"),
        ("Apiiro", "apiiro", "apiiro.com"),
        ("Cycode", "cycode", "cycode.com"),
        ("Scribe Security", "scribesecurity", "scribesecurity.com"),
        ("Kubescape", "kubescape", "kubescape.io"),
        ("ARMO", "armo", "armosec.io"),
        ("Kubiya", "kubiya", "kubiya.ai"),
        ("Salt Security", "saltsecurity", "salt.security"),
        ("Traceable AI", "traceable", "traceable.ai"),
        ("Neosec", "neosec", "neosec.io"),
        ("FireTail", "firetail", "firetail.io"),
        ("Escape", "escape", "escape.tech"),
        ("Pynt", "pynt", "pynt.io"),
        ("LeakSignal", "leaksignal", "leaksignal.com"),
        ("Aserto", "aserto", "aserto.com"),
        ("Permit.io", "permit", "permit.io"),
        ("Oso", "oso", "osohq.com"),
        ("Cerbos", "cerbos", "cerbos.dev"),
        ("Auth0", "auth0", "auth0.com"),
        ("Okta", "okta", "okta.com"),
        ("Ping Identity", "pingidentity", "pingidentity.com"),
        ("ForgeRock", "forgerock", "forgerock.com"),
        ("OneLogin", "onelogin", "onelogin.com"),
        ("JumpCloud", "jumpcloud", "jumpcloud.com"),
        ("Foxpass", "foxpass", "foxpass.com"),
        ("Teleport", "teleport", "goteleport.com"),
        ("StrongDM", "strongdm", "strongdm.com"),
        ("Boundary", "boundary", "boundary.com"),
        ("Twingate", "twingate", "twingate.com"),
        ("Tailscale", "tailscale", "tailscale.com"),
        ("ZeroTier", "zerotier", "zerotier.com"),
        ("NetBird", "netbird", "netbird.io"),
        ("Headscale", "headscale", "headscale.net"),
        ("WireGuard", "wireguard", "wireguard.com"),
        ("OpenVPN", "openvpn", "openvpn.net"),
        ("Pritunl", "pritunl", "pritunl.com"),
        ("SentinelOne", "sentinelone", "sentinelone.com"),
        ("CyberArk", "cyberark", "cyberark.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("Aqua Security", "aqua-security", "aquasec.com"),
        ("BigID", "bigid", "bigid.com"),
        ("Wiz", "wiz", "wiz.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Armis", "armis", "armis.com"),
        ("Ping Identity", "pingidentity", "pingidentity.com"),
        ("JumpCloud", "jumpcloud", "jumpcloud.com"),
        ("Twingate", "twingate", "twingate.com"),
        ("Tailscale", "tailscale", "tailscale.com"),
        ("ZeroTier", "zerotier", "zerotier.com"),
        ("NetBird", "netbird", "netbird.io"),
    ],
    "fintech_extended": [
        ("Payoneer", "payoneer", "payoneer.com"),
        ("Melio", "melio", "melio.com"),
        ("Pagaya", "pagaya", "pagaya.com"),
        ("Next Insurance", "next-insurance", "nextinsurance.com"),
        ("Hippo", "hippo", "hippo.com"),
        ("Wefox", "wefox", "wefox.com"),
        ("Lemonade", "lemonade", "lemonade.com"),
        ("FundGuard", "fundguard", "fundguard.com"),
        ("BlueVine", "bluevine", "bluevine.com"),
        ("Kabbage", "kabbage", "kabbage.com"),
        ("Nayax", "nayax", "nayax.com"),
        ("Bit2C", "bit2c", "bit2c.co.il"),
        ("CoinMama", "coinmama", "coinmama.com"),
        ("Simplex", "simplex", "simplex.com"),
        ("MoonPay", "moonpay", "moonpay.com"),
        ("Fireblocks", "fireblocks", "fireblocks.com"),
        ("Unbound Tech", "unboundtech", "unboundtech.com"),
        ("ZenGo", "zengo", "zengo.com"),
        ("StarkWare", "starkware", "starkware.co"),
        ("Matter Labs", "matterlabs", "matterlabs.dev"),
        ("Immutable", "immutable", "immutable.com"),
        ("Polygon", "polygon", "polygon.technology"),
        ("StarkNet", "starknet", "starknet.io"),
        ("ZKSync", "zksync", "zksync.io"),
        ("Arbitrum", "arbitrum", "arbitrum.io"),
        ("Optimism", "optimism", "optimism.io"),
        ("Base", "base", "base.org"),
        ("Linea", "linea", "linea.build"),
        ("Scroll", "scroll", "scroll.io"),
        ("Taiko", "taiko", "taiko.xyz"),
        ("Mantle", "mantle", "mantle.xyz"),
        ("Mode", "mode", "mode.network"),
        ("Blast", "blast", "blast.io"),
        ("Metis", "metis", "metis.io"),
        ("Boba", "boba", "boba.network"),
        ("BlueVine", "bluevine", "bluevine.com"),
        ("Kabbage", "kabbage", "kabbage.com"),
        ("Nayax", "nayax", "nayax.com"),
        ("Bit2C", "bit2c", "bit2c.co.il"),
        ("CoinMama", "coinmama", "coinmama.com"),
        ("Simplex", "simplex", "simplex.com"),
        ("MoonPay", "moonpay", "moonpay.com"),
        ("Fireblocks", "fireblocks", "fireblocks.com"),
        ("Unbound Tech", "unboundtech", "unboundtech.com"),
        ("ZenGo", "zengo", "zengo.com"),
        ("StarkWare", "starkware", "starkware.co"),
        ("Matter Labs", "matterlabs", "matterlabs.dev"),
        ("Immutable", "immutable", "immutable.com"),
        ("Polygon", "polygon", "polygon.technology"),
        ("StarkNet", "starknet", "starknet.io"),
        ("ZKSync", "zksync", "zksync.io"),
        ("Arbitrum", "arbitrum", "arbitrum.io"),
        ("Optimism", "optimism", "optimism.io"),
        ("Base", "base", "base.org"),
        ("Linea", "linea", "linea.build"),
        ("Scroll", "scroll", "scroll.io"),
        ("Taiko", "taiko", "taiko.xyz"),
        ("Mantle", "mantle", "mantle.xyz"),
        ("Mode", "mode", "mode.network"),
        ("Blast", "blast", "blast.io"),
        ("Metis", "metis", "metis.io"),
        ("Boba", "boba", "boba.network"),
        ("Ape", "ape", "apecoin.com"),
        ("Pepe", "pepe", "pepe.vip"),
        ("Floki", "floki", "floki.com"),
        ("Shiba", "shiba", "shibatoken.com"),
        ("Doge", "doge", "dogecoin.com"),
    ],
        ("Sisense", "sisense", "sisense.com"),
        ("Panoply", "panoply", "panoply.io"),
        ("Incorta", "incorta", "incorta.com"),
        ("Qubole", "qubole", "qubole.com"),
        ("DataBricks Israel", "databricks", "databricks.com"),
        ("Snowflake Israel", "snowflake", "snowflake.com"),
        ("MongoDB Israel", "mongodb", "mongodb.com"),
        ("Redis Israel", "redis", "redis.com"),
        ("Elastic Israel", "elastic", "elastic.co"),
        ("Confluent Israel", "confluent", "confluent.io"),
        ("HashiCorp Israel", "hashicorp", "hashicorp.com"),
        ("GitLab Israel", "gitlab", "gitlab.com"),
        ("GitHub Israel", "github", "github.com"),
        ("Atlassian Israel", "atlassian", "atlassian.com"),
        ("JFrog", "jfrog", "jfrog.com"),
        ("Snyk", "snyk", "snyk.io"),
        ("Aqua Security", "aqua-security", "aquasec.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("WhiteSource", "whitesource", "whitesourcesoftware.com"),
        ("SonarSource", "sonarsource", "sonarsource.com"),
        ("Veracode", "veracode", "veracode.com"),
        ("Contrast Security", "contrastsecurity", "contrastsecurity.com"),
        ("ShiftLeft", "shiftleft", "shiftleft.io"),
        ("OX Security", "oxsecurity", "ox.security"),
        ("Apiiro", "apiiro", "apiiro.com"),
        ("Bridgecrew", "bridgecrew", "bridgecrew.io"),
        ("Ermetic", "ermetic", "ermetic.com"),
        ("Orca Security", "orcasecurity", "orca.security"),
        ("Wiz", "wiz", "wiz.io"),
        ("Noname Security", "nonamesecurity", "nonamesecurity.com"),
        ("Cyera", "cyera", "cyera.io"),
        ("Armis", "armis", "armis.com"),
        ("SentinelOne", "sentinelone", "sentinelone.com"),
        ("CyberArk", "cyberark", "cyberark.com"),
        ("Checkmarx", "checkmarx", "checkmarx.com"),
        ("IronSource", "ironsource", "ironsrc.com"),
        ("Gong", "gong", "gong.io"),
        ("Snyk", "snyk", "snyk.io"),
        ("Lemonade", "lemonade", "lemonade.com"),
        ("Fiverr", "fiverr", "fiverr.com"),
    ],
}

# Known provider assignments for specific companies
provider_overrides: Dict[str, List[str]] = {
    # Lever
    "walkme": ["lever"],
    "cloudinary": ["lever"],
    "source": ["lever"],
    "jumpcloud": ["lever"],
    "twingate": ["lever"],
    "zerotier": ["lever", "smartrecruiters"],
    "moonpay": ["lever"],
    "sonarsource": ["lever"],
    # Ashby
    "snyk": ["ashby"],
    "lemonade": ["ashby"],
    "moonactive": ["ashby"],
    "netbird": ["ashby"],
    "oso": ["ashby"],
    "escape": ["ashby"],
    # SmartRecruiters
    "gong": ["smartrecruiters"],
    "fiverr": ["smartrecruiters"],
    "armis": ["smartrecruiters"],
    "coinmama": ["smartrecruiters"],
    "zerotier": ["smartrecruiters"],
    # Workable
    "wix": ["workable"],
    "monday": ["workable"],
    # Greenhouse (default for most)
}

def build_final_list() -> List[Dict]:
    """Build the final deduplicated company list with providers."""
    # Start with working companies
    company_map: Dict[str, Dict] = {}
    
    for name, slug, domain, providers in working_companies:
        slug_lower = slug.lower()
        if slug_lower not in company_map:
            company_map[slug_lower] = {
                "name": name,
                "slug": slug,
                "domain": domain,
                "providers": providers
            }
        else:
            # Merge providers
            for p in providers:
                if p not in company_map[slug_lower]["providers"]:
                    company_map[slug_lower]["providers"].append(p)
    
    # Add additional companies from categories
    for category, companies in additional_by_category.items():
        for name, slug, domain in companies:
            slug_lower = slug.lower()
            providers = provider_overrides.get(slug_lower, ["greenhouse"])
            if slug_lower not in company_map:
                company_map[slug_lower] = {
                    "name": name,
                    "slug": slug,
                    "domain": domain,
                    "providers": providers
                }
            else:
                # Merge providers
                for p in providers:
                    if p not in company_map[slug_lower]["providers"]:
                        company_map[slug_lower]["providers"].append(p)
    
    # Apply provider overrides
    for slug, providers in provider_overrides.items():
        slug_lower = slug.lower()
        if slug_lower in company_map:
            company_map[slug_lower]["providers"] = providers
    
    # Convert to list
    final_list = list(company_map.values())
    
    # Sort by name
    final_list.sort(key=lambda x: x["name"].lower())
    
    return final_list

if __name__ == "__main__":
    final_list = build_final_list()
    
    print(f"Total unique companies: {len(final_list)}")
    
    # Count by provider
    provider_counts = {}
    for c in final_list:
        for p in c.get("providers", []):
            provider_counts[p] = provider_counts.get(p, 0) + 1
    print(f"Provider distribution: {provider_counts}")
    
    # Show sample
    print("\nSample companies:")
    for c in final_list[:20]:
        print(f"  {c['name']} ({c['slug']}) - {c['providers']}")
    
    # Output
    output = {
        "_comment": "Israeli tech companies that publish jobs on a public ATS. Each provider is a documented unauthenticated JSON API (no key, no login, no HTML scraping), so these rows are the employer's own postings with full descriptions. Add a company by probing its ATS slug: python3 agents/scan_jobs.py --ats-probe <slug>. Only providers returning >0 jobs are listed; the scanner skips the rest. `slug` is the ATS board identifier, not always the domain.",
        "companies": final_list
    }
    
    with open("agents/config/ats-companies.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    
    print(f"\nWritten {len(final_list)} companies to agents/config/ats-companies.json")